// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulknlrckbrwkxpakdrfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsa25scmNrYnJ3a3hwYWtkcmZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDc1NDgsImV4cCI6MjA2NDgyMzU0OH0.U1uH3mNtoK8IM7xwc4ZZ8881ezXFWSPO7gTmkBew9xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);